version: '3.8'

services:
  postgres:
    image: postgres:latest
    ports:
      - "5433:5433"
    environment:
      POSTGRES_DB: student-registration
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      POSTGRES_DB: student-registration
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_HOST: postgres
    depends_on:
      - postgres